### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by plijnzaad**

### CODE REVIEW

**Comment by plijnzaad** [comment]
various edits, mostly formatting and using syntactic variables, and some restructuring

**Comment by kcranston** [comment]
We have re-organized our lesson material into separate repositories for each lesson. So, this PR needs to be against the [shell-ecology](https://github.com/datacarpentry/shell-ecology) repo. @plijnzaad - can you repeat again the other repo? Sorry for the hassle (and thanks for fixing this stuff!). I could make the changes there, but don't want to lose the authorship history.

**Comment by plijnzaad** [comment]
Hi Karen,

Sorry, I don't know how to create this pull request, not having much github
experience. In datacarpentry/plijnzaad/typos, I only can create PR's
against datacarpentry/archive-datacarpentry, and to various people's forks
of datacarpentry. I don't see the option to generate it for shell-ecology,
it's not a proper fork apparently. Should I create some sort of patch, and
if so, how? Thanks,

Philip

**Comment by kcranston** [comment]
I would fork the [shell-ecology](https://github.com/datacarpentry/shell-ecology) lesson, make the changes to the shell.md file in that repo (which you could do by copying over the file from your local copy of this repo) and then create a new PR against shell-ecology. Does that make sense?

**Comment by hlapp** [comment]
I notice that one problem is that the shell-ecology lesson lacks the cheatsheet directory (and thus cheatsheets). How do want to deal with this?

**Comment by plijnzaad** [comment]
ah, that makes sense, done that. Thanks,

Philip
​

**Comment by hlapp** [comment]
Ah - I see @plijnzaad already figured it all out in datacarpentry/shell-ecology#3. Awesome!

**Comment by plijnzaad** [comment]
> Ah - I see @plijnzaad <https://github.com/plijnzaad> already figured it
> all out in datacarpentry/shell-ecology#3
> <https://github.com/datacarpentry/shell-ecology/pull/3>. Awesome!
>
>
ah, yes, getting there. And the differences between ./shell.md and
cheatsheets/shell.md were minor, so I followed Karen's advice and just
copied my cheatsheets/shell.md.  I guess  all changes are now in
shell-ecology, including those from datacarpentry/lessons/shell.md.

Cheers,

Philip



-- 
Philip Lijnzaad
Griffensteijnselaan 73
3703 AD   ZEIST
030 6912611
06 27455483

**Comment by kcranston** [comment]
Awesome! Thanks, @plijnzaad

**Pull request closed without merging**
